export enum TEAM_PERMISSIONS {
	MANAGE_MEMBERS = 1 << 0,
	DELETE_TEAM = 1 << 3,
	DELETE_DEPLOYMENT = 1 << 4,
	DELETE_CONTAINER = 1 << 5,
	UPDATE_CONTAINER_STATE = 1 << 6,
	READ_DEPLOYMENTS = 1 << 7,
	CREATE_DEPLOYMENT = 1 << 8,
	CREATE_CONTAINER = 1 << 9,
	UPDATE_CONTAINER_CONFIG = 1 << 10,
	CREATE_STREAM = 1 << 11,
	READ_STREAM = 1 << 12,
	DELETE_STREAM = 1 << 13,
	CREATE_STREAM_PRODUCER = 1 << 14,
	CREATE_SECRET_KEY = 1 << 15,
	DELETE_SECRET_KEY = 1 << 16,
	READ_SECRET_KEYS = 1 << 17,
	READ_CONTAINER_LOGS = 1 << 18,
}

export enum BROAD_TEAM_PERMISSIONS {
	MANAGE_MEMBERS = TEAM_PERMISSIONS.MANAGE_MEMBERS,
	MANAGE_SECRET_KEYS = TEAM_PERMISSIONS.CREATE_SECRET_KEY |
		TEAM_PERMISSIONS.DELETE_SECRET_KEY |
		TEAM_PERMISSIONS.READ_SECRET_KEYS,
	MANAGE_STREAMS = TEAM_PERMISSIONS.CREATE_STREAM |
		TEAM_PERMISSIONS.READ_STREAM |
		TEAM_PERMISSIONS.DELETE_STREAM |
		TEAM_PERMISSIONS.CREATE_STREAM_PRODUCER,
	DELETE_TEAM = TEAM_PERMISSIONS.DELETE_TEAM,
	MANAGE_DEPLOYMENTS = TEAM_PERMISSIONS.DELETE_DEPLOYMENT |
		TEAM_PERMISSIONS.READ_DEPLOYMENTS |
		TEAM_PERMISSIONS.CREATE_DEPLOYMENT,
	MANAGE_CONTAINERS = TEAM_PERMISSIONS.DELETE_CONTAINER |
		TEAM_PERMISSIONS.UPDATE_CONTAINER_STATE |
		TEAM_PERMISSIONS.CREATE_CONTAINER |
		TEAM_PERMISSIONS.UPDATE_CONTAINER_CONFIG |
		TEAM_PERMISSIONS.READ_CONTAINER_LOGS,
}
