export enum PROJECT_PERMISSIONS {
	MANAGE_MEMBERS = 1 << 0,
	DELETE_PROJECT = 1 << 3,
	DELETE_DEPLOYMENT = 1 << 4,
	DELETE_CONTAINER = 1 << 5,
	UPDATE_CONTAINER_STATE = 1 << 6,
	READ_DEPLOYMENTS = 1 << 7,
	CREATE_DEPLOYMENT = 1 << 8,
	CREATE_CONTAINER = 1 << 9,
	UPDATE_CONTAINER_CONFIG = 1 << 10,
	CREATE_STREAM = 1 << 11,
	READ_STREAM = 1 << 12,
	DELETE_STREAM = 1 << 13,
	CREATE_STREAM_PRODUCER = 1 << 14,
	CREATE_PROJECT_TOKEN = 1 << 15,
	DELETE_PROJECT_TOKEN = 1 << 16,
	READ_PROJECT_TOKENS = 1 << 17,
	READ_CONTAINER_LOGS = 1 << 18,
}

export enum BROAD_PROJECT_PERMISSIONS {
	MANAGE_MEMBERS = PROJECT_PERMISSIONS.MANAGE_MEMBERS,
	MANAGE_PROJECT_TOKENS = PROJECT_PERMISSIONS.CREATE_PROJECT_TOKEN |
		PROJECT_PERMISSIONS.DELETE_PROJECT_TOKEN |
		PROJECT_PERMISSIONS.READ_PROJECT_TOKENS,
	MANAGE_STREAMS = PROJECT_PERMISSIONS.CREATE_STREAM |
		PROJECT_PERMISSIONS.READ_STREAM |
		PROJECT_PERMISSIONS.DELETE_STREAM |
		PROJECT_PERMISSIONS.CREATE_STREAM_PRODUCER,
	DELETE_PROJECT = PROJECT_PERMISSIONS.DELETE_PROJECT,
	MANAGE_DEPLOYMENTS = PROJECT_PERMISSIONS.DELETE_DEPLOYMENT |
		PROJECT_PERMISSIONS.READ_DEPLOYMENTS |
		PROJECT_PERMISSIONS.CREATE_DEPLOYMENT,
	MANAGE_CONTAINERS = PROJECT_PERMISSIONS.DELETE_CONTAINER |
		PROJECT_PERMISSIONS.UPDATE_CONTAINER_STATE |
		PROJECT_PERMISSIONS.CREATE_CONTAINER |
		PROJECT_PERMISSIONS.UPDATE_CONTAINER_CONFIG |
		PROJECT_PERMISSIONS.READ_CONTAINER_LOGS,
}

export const permissions = {
	add(value: number, flag: PROJECT_PERMISSIONS | BROAD_PROJECT_PERMISSIONS) {
		return value | flag;
	},

	test(value: number, flag: PROJECT_PERMISSIONS | BROAD_PROJECT_PERMISSIONS) {
		return (value & flag) === flag;
	},

	subtract(
		value: number,
		flag: PROJECT_PERMISSIONS | BROAD_PROJECT_PERMISSIONS,
	) {
		return value & ~flag;
	},
};
